// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWvLmltn7j5FwgSB9toeGOd6Z47TIxM5E',
    appId: '1:74067470392:web:98ede2ed03e3a446695ecd',
    messagingSenderId: '74067470392',
    projectId: 'authapp-e1b34',
    authDomain: 'authapp-e1b34.firebaseapp.com',
    storageBucket: 'authapp-e1b34.appspot.com',
    measurementId: 'G-LRJBVGZ6Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5rM8opDNZdnEbUZn8EzCvlMnIJdXGBs4',
    appId: '1:74067470392:android:bf3315e54f28ce58695ecd',
    messagingSenderId: '74067470392',
    projectId: 'authapp-e1b34',
    storageBucket: 'authapp-e1b34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtp9_F0tZG-7Z7fTBEbAfg7aqaknL-Ea8',
    appId: '1:74067470392:ios:33ba258c371e9e74695ecd',
    messagingSenderId: '74067470392',
    projectId: 'authapp-e1b34',
    storageBucket: 'authapp-e1b34.appspot.com',
    iosBundleId: 'com.example.projectAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtp9_F0tZG-7Z7fTBEbAfg7aqaknL-Ea8',
    appId: '1:74067470392:ios:33ba258c371e9e74695ecd',
    messagingSenderId: '74067470392',
    projectId: 'authapp-e1b34',
    storageBucket: 'authapp-e1b34.appspot.com',
    iosBundleId: 'com.example.projectAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWvLmltn7j5FwgSB9toeGOd6Z47TIxM5E',
    appId: '1:74067470392:web:ae15ccaa3fda7a4d695ecd',
    messagingSenderId: '74067470392',
    projectId: 'authapp-e1b34',
    authDomain: 'authapp-e1b34.firebaseapp.com',
    storageBucket: 'authapp-e1b34.appspot.com',
    measurementId: 'G-XWS4E0T9XP',
  );

}